### ISSUE TITLE
Games not playable

### ISSUE THREAD

**Issue by bonxz** [koala9712/DiscordActivities#4]
![image](https://user-images.githubusercontent.com/61289944/153670298-137792cb-e090-4541-a112-5da79cc65898.png)

Hello, I have set everything as described in the description. The bot makes the message in the text channel but the game does not open. Both buttons are grayed out.

**Comment by koala9712** [comment]
Oh hey! Just checked this, apologies for the delay.

You need to click the link given by the bot, and not the buttons itself.
The bot is more of a "hack" around discord's limitations, not exactly the "right" way to get games in your own guild.
